version: "2"
services:
  nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      depends_on:
        - fpm
      ports:
          - "8082:80"
      links:
          - fpm
      tty: true
  fpm:
      build:
        context: .
        dockerfile: Dockerfile.dev
      tty: true
      ports:
        - "9000:9000"